### ISSUE TITLE
Config File error

### ISSUE THREAD

**Issue by muneebasad** [mhamdan91/cnn_vhdl_generator#2]
while I run the program. after loading config files. it pops up ' Config File has been removed'. please help to resolve.

<img width="427" alt="config file issue" src="https://user-images.githubusercontent.com/42151663/44189508-baddae00-a13c-11e8-8ab1-81751dbeadc0.png">

**Comment by mhamdanx** [comment]
The files with "weights" name in them are random generated weights.
Config files are those which do not have the name "weight" in them

**Comment by muneebasad** [comment]
yes I get that. whenever I click on load configuration button, then select any config file. once I click on validate model entries then mentioned above error pops up. 
so what is mentioned error all about ?

**Comment by mhamdanx** [comment]
I've just put a tutorial on how to use the tool
check out the main page: https://github.com/mhamdan91/cnn_vhdl_generator
