### ISSUE TITLE
Vivado Simulation

### ISSUE THREAD

**Issue by hamoudyounesyounes** [mhamdan91/cnn_vhdl_generator#3]
After successfully generating everything, I tried to create a Vivado project to simulate the complete CNN. But, a lot of errors popup such as invalid pin direction for some pins, variable size mismatch. Can you test that and provide a guide on how to simulate the CNN?

**Comment by mhamdan91** [comment]
I am guessing the errors are stemming from the TOP_LEVEL module interface. 
That is just a template and should only be used as a reference. 
Your should write your own interface with the accelerator. 
Hope this help

**Comment by hamoudyounesyounes** [comment]
I'll look into it. But did you try it for your own TOP_MODULE? Also, if I may ask, are you going to support decimal weights reading from files?
Keep the good work!!! Thanks

**Comment by mhamdan91** [comment]
Not any time soon.
